package com.vscode.android.ui.theme

import androidx.annotation.ColorInt

data class ThemeColors(
    @ColorInt val background: Int = DarkTheme.background,
    @ColorInt val foreground: Int = DarkTheme.foreground,
    @ColorInt val sidebarBackground: Int = DarkTheme.sidebarBackground,
    @ColorInt val activityBarBackground: Int = DarkTheme.activityBarBackground,
    @ColorInt val activityBarForeground: Int = DarkTheme.activityBarForeground,
    @ColorInt val activityBarActiveForeground: Int = DarkTheme.activityBarActiveForeground,
    @ColorInt val activityBarInactiveForeground: Int = DarkTheme.activityBarInactiveForeground,
    @ColorInt val activityBarActiveBorder: Int = DarkTheme.activityBarActiveBorder,
    @ColorInt val activityBarBadgeBackground: Int = DarkTheme.activityBarBadgeBackground,
    @ColorInt val activityBarBadgeForeground: Int = DarkTheme.activityBarBadgeForeground,
    @ColorInt val editorBackground: Int = DarkTheme.editorBackground,
    @ColorInt val editorForeground: Int = DarkTheme.editorForeground,
    @ColorInt val editorLineHighlight: Int = DarkTheme.editorLineHighlight,
    @ColorInt val editorSelectionBackground: Int = DarkTheme.editorSelectionBackground,
    @ColorInt val editorLineNumber: Int = DarkTheme.editorLineNumber,
    @ColorInt val editorLineNumberActive: Int = DarkTheme.editorLineNumberActive,
    @ColorInt val editorCursor: Int = DarkTheme.editorCursor,
    @ColorInt val editorGutterBackground: Int = DarkTheme.editorGutterBackground,
    @ColorInt val editorWidgetBackground: Int = DarkTheme.editorWidgetBackground,
    @ColorInt val statusBarBackground: Int = DarkTheme.statusBarBackground,
    @ColorInt val statusBarForeground: Int = DarkTheme.statusBarForeground,
    @ColorInt val statusBarItemHoverBackground: Int = DarkTheme.statusBarItemHoverBackground,
    @ColorInt val tabBackground: Int = DarkTheme.tabBackground,
    @ColorInt val tabActiveBackground: Int = DarkTheme.tabActiveBackground,
    @ColorInt val tabInactiveBackground: Int = DarkTheme.tabInactiveBackground,
    @ColorInt val tabActiveForeground: Int = DarkTheme.tabActiveForeground,
    @ColorInt val tabInactiveForeground: Int = DarkTheme.tabInactiveForeground,
    @ColorInt val tabActiveBorderTop: Int = DarkTheme.tabActiveBorderTop,
    @ColorInt val tabBorder: Int = DarkTheme.tabBorder,
    @ColorInt val panelBackground: Int = DarkTheme.panelBackground,
    @ColorInt val panelTitleActiveForeground: Int = DarkTheme.panelTitleActiveForeground,
    @ColorInt val panelTitleInactiveForeground: Int = DarkTheme.panelTitleInactiveForeground,
    @ColorInt val panelTitleActiveBorder: Int = DarkTheme.panelTitleActiveBorder,
    @ColorInt val panelInputBorder: Int = DarkTheme.panelInputBorder,
    @ColorInt val terminalBackground: Int = DarkTheme.terminalBackground,
    @ColorInt val terminalForeground: Int = DarkTheme.terminalForeground,
    @ColorInt val terminalAnsiBlack: Int = DarkTheme.terminalAnsiBlack,
    @ColorInt val terminalAnsiRed: Int = DarkTheme.terminalAnsiRed,
    @ColorInt val terminalAnsiGreen: Int = DarkTheme.terminalAnsiGreen,
    @ColorInt val terminalAnsiYellow: Int = DarkTheme.terminalAnsiYellow,
    @ColorInt val terminalAnsiBlue: Int = DarkTheme.terminalAnsiBlue,
    @ColorInt val terminalAnsiMagenta: Int = DarkTheme.terminalAnsiMagenta,
    @ColorInt val terminalAnsiCyan: Int = DarkTheme.terminalAnsiCyan,
    @ColorInt val terminalAnsiWhite: Int = DarkTheme.terminalAnsiWhite,
    @ColorInt val terminalAnsiBrightBlack: Int = DarkTheme.terminalAnsiBrightBlack,
    @ColorInt val terminalAnsiBrightRed: Int = DarkTheme.terminalAnsiBrightRed,
    @ColorInt val terminalAnsiBrightGreen: Int = DarkTheme.terminalAnsiBrightGreen,
    @ColorInt val terminalAnsiBrightYellow: Int = DarkTheme.terminalAnsiBrightYellow,
    @ColorInt val terminalAnsiBrightBlue: Int = DarkTheme.terminalAnsiBrightBlue,
    @ColorInt val terminalAnsiBrightMagenta: Int = DarkTheme.terminalAnsiBrightMagenta,
    @ColorInt val terminalAnsiBrightCyan: Int = DarkTheme.terminalAnsiBrightCyan,
    @ColorInt val terminalAnsiBrightWhite: Int = DarkTheme.terminalAnsiBrightWhite,
    @ColorInt val textPrimary: Int = DarkTheme.textPrimary,
    @ColorInt val textSecondary: Int = DarkTheme.textSecondary,
    @ColorInt val textDisabled: Int = DarkTheme.textDisabled,
    @ColorInt val textLink: Int = DarkTheme.textLink,
    @ColorInt val accentBlue: Int = DarkTheme.accentBlue,
    @ColorInt val accentGreen: Int = DarkTheme.accentGreen,
    @ColorInt val accentYellow: Int = DarkTheme.accentYellow,
    @ColorInt val accentRed: Int = DarkTheme.accentRed,
    @ColorInt val accentPurple: Int = DarkTheme.accentPurple,
    @ColorInt val accentCyan: Int = DarkTheme.accentCyan,
    @ColorInt val accentOrange: Int = DarkTheme.accentOrange,
    @ColorInt val inputBackground: Int = DarkTheme.inputBackground,
    @ColorInt val inputForeground: Int = DarkTheme.inputForeground,
    @ColorInt val inputBorder: Int = DarkTheme.inputBorder,
    @ColorInt val inputPlaceholderForeground: Int = DarkTheme.inputPlaceholderForeground,
    @ColorInt val inputFocusBorder: Int = DarkTheme.inputFocusBorder,
    @ColorInt val buttonBackground: Int = DarkTheme.buttonBackground,
    @ColorInt val buttonForeground: Int = DarkTheme.buttonForeground,
    @ColorInt val buttonSecondaryBackground: Int = DarkTheme.buttonSecondaryBackground,
    @ColorInt val buttonSecondaryForeground: Int = DarkTheme.buttonSecondaryForeground,
    @ColorInt val dropdownBackground: Int = DarkTheme.dropdownBackground,
    @ColorInt val dropdownForeground: Int = DarkTheme.dropdownForeground,
    @ColorInt val dropdownBorder: Int = DarkTheme.dropdownBorder,
    @ColorInt val listActiveBackground: Int = DarkTheme.listActiveBackground,
    @ColorInt val listHoverBackground: Int = DarkTheme.listHoverBackground,
    @ColorInt val badgeBackground: Int = DarkTheme.badgeBackground,
    @ColorInt val badgeForeground: Int = DarkTheme.badgeForeground,
    @ColorInt val divider: Int = DarkTheme.divider,
    @ColorInt val border: Int = DarkTheme.border,
    @ColorInt val focusBorder: Int = DarkTheme.focusBorder,
    @ColorInt val errorForeground: Int = DarkTheme.errorForeground,
    @ColorInt val warningForeground: Int = DarkTheme.warningForeground,
    @ColorInt val infoForeground: Int = DarkTheme.infoForeground,
    @ColorInt val successForeground: Int = DarkTheme.successForeground,
    @ColorInt val scrollbarSliderBackground: Int = DarkTheme.scrollbarSliderBackground,
    @ColorInt val scrollbarSliderHoverBackground: Int = DarkTheme.scrollbarSliderHoverBackground,
    @ColorInt val scrollbarSliderActiveBackground: Int = DarkTheme.scrollbarSliderActiveBackground,
    @ColorInt val menuBackground: Int = DarkTheme.menuBackground,
    @ColorInt val menuForeground: Int = DarkTheme.menuForeground,
    @ColorInt val menuSelectionBackground: Int = DarkTheme.menuSelectionBackground,
    @ColorInt val notificationBackground: Int = DarkTheme.notificationBackground,
    @ColorInt val notificationForeground: Int = DarkTheme.notificationForeground,
    @ColorInt val keyword: Int = DarkTheme.keyword,
    @ColorInt val string: Int = DarkTheme.string,
    @ColorInt val number: Int = DarkTheme.number,
    @ColorInt val comment: Int = DarkTheme.comment,
    @ColorInt val type: Int = DarkTheme.type,
    @ColorInt val function: Int = DarkTheme.function,
    @ColorInt val variable: Int = DarkTheme.variable,
    @ColorInt val constant: Int = DarkTheme.constant,
    @ColorInt val operator: Int = DarkTheme.operator,
    @ColorInt val className: Int = DarkTheme.className,
    @ColorInt val parameter: Int = DarkTheme.parameter,
    @ColorInt val property: Int = DarkTheme.property,
    @ColorInt val regex: Int = DarkTheme.regex,
    @ColorInt val tag: Int = DarkTheme.tag,
    @ColorInt val attributeName: Int = DarkTheme.attributeName,
    @ColorInt val attributeValue: Int = DarkTheme.attributeValue,
    @ColorInt val titleBarBackground: Int = DarkTheme.titleBarBackground,
    @ColorInt val sidebarSectionHeaderBackground: Int = DarkTheme.sidebarSectionHeaderBackground,
    @ColorInt val sidebarSectionHeaderForeground: Int = DarkTheme.sidebarSectionHeaderForeground,
    @ColorInt val sidebarListActiveBackground: Int = DarkTheme.sidebarListActiveBackground,
    @ColorInt val sidebarListInactiveBackground: Int = DarkTheme.sidebarListInactiveBackground
) {
    companion object {
        val defaultDarkTheme: ThemeColors = ThemeColors()

        val lightTheme: ThemeColors = ThemeColors(
            background = LightTheme.background,
            foreground = LightTheme.foreground,
            sidebarBackground = LightTheme.sidebarBackground,
            activityBarBackground = LightTheme.activityBarBackground,
            activityBarForeground = LightTheme.activityBarForeground,
            activityBarActiveForeground = LightTheme.activityBarActiveForeground,
            activityBarInactiveForeground = LightTheme.activityBarInactiveForeground,
            activityBarActiveBorder = LightTheme.activityBarActiveBorder,
            activityBarBadgeBackground = LightTheme.activityBarBadgeBackground,
            activityBarBadgeForeground = LightTheme.activityBarBadgeForeground,
            editorBackground = LightTheme.editorBackground,
            editorForeground = LightTheme.editorForeground,
            editorLineHighlight = LightTheme.editorLineHighlight,
            editorSelectionBackground = LightTheme.editorSelectionBackground,
            editorLineNumber = LightTheme.editorLineNumber,
            editorLineNumberActive = LightTheme.editorLineNumberActive,
            editorCursor = LightTheme.editorCursor,
            editorGutterBackground = LightTheme.editorGutterBackground,
            editorWidgetBackground = LightTheme.editorWidgetBackground,
            statusBarBackground = LightTheme.statusBarBackground,
            statusBarForeground = LightTheme.statusBarForeground,
            statusBarItemHoverBackground = LightTheme.statusBarItemHoverBackground,
            tabBackground = LightTheme.tabBackground,
            tabActiveBackground = LightTheme.tabActiveBackground,
            tabInactiveBackground = LightTheme.tabInactiveBackground,
            tabActiveForeground = LightTheme.tabActiveForeground,
            tabInactiveForeground = LightTheme.tabInactiveForeground,
            tabActiveBorderTop = LightTheme.tabActiveBorderTop,
            tabBorder = LightTheme.tabBorder,
            panelBackground = LightTheme.panelBackground,
            panelTitleActiveForeground = LightTheme.panelTitleActiveForeground,
            panelTitleInactiveForeground = LightTheme.panelTitleInactiveForeground,
            panelTitleActiveBorder = LightTheme.panelTitleActiveBorder,
            panelInputBorder = LightTheme.panelInputBorder,
            terminalBackground = LightTheme.terminalBackground,
            terminalForeground = LightTheme.terminalForeground,
            terminalAnsiBlack = LightTheme.terminalAnsiBlack,
            terminalAnsiRed = LightTheme.terminalAnsiRed,
            terminalAnsiGreen = LightTheme.terminalAnsiGreen,
            terminalAnsiYellow = LightTheme.terminalAnsiYellow,
            terminalAnsiBlue = LightTheme.terminalAnsiBlue,
            terminalAnsiMagenta = LightTheme.terminalAnsiMagenta,
            terminalAnsiCyan = LightTheme.terminalAnsiCyan,
            terminalAnsiWhite = LightTheme.terminalAnsiWhite,
            terminalAnsiBrightBlack = LightTheme.terminalAnsiBrightBlack,
            terminalAnsiBrightRed = LightTheme.terminalAnsiBrightRed,
            terminalAnsiBrightGreen = LightTheme.terminalAnsiBrightGreen,
            terminalAnsiBrightYellow = LightTheme.terminalAnsiBrightYellow,
            terminalAnsiBrightBlue = LightTheme.terminalAnsiBrightBlue,
            terminalAnsiBrightMagenta = LightTheme.terminalAnsiBrightMagenta,
            terminalAnsiBrightCyan = LightTheme.terminalAnsiBrightCyan,
            terminalAnsiBrightWhite = LightTheme.terminalAnsiBrightWhite,
            textPrimary = LightTheme.textPrimary,
            textSecondary = LightTheme.textSecondary,
            textDisabled = LightTheme.textDisabled,
            textLink = LightTheme.textLink,
            accentBlue = LightTheme.accentBlue,
            accentGreen = LightTheme.accentGreen,
            accentYellow = LightTheme.accentYellow,
            accentRed = LightTheme.accentRed,
            accentPurple = LightTheme.accentPurple,
            accentCyan = LightTheme.accentCyan,
            accentOrange = LightTheme.accentOrange,
            inputBackground = LightTheme.inputBackground,
            inputForeground = LightTheme.inputForeground,
            inputBorder = LightTheme.inputBorder,
            inputPlaceholderForeground = LightTheme.inputPlaceholderForeground,
            inputFocusBorder = LightTheme.inputFocusBorder,
            buttonBackground = LightTheme.buttonBackground,
            buttonForeground = LightTheme.buttonForeground,
            buttonSecondaryBackground = LightTheme.buttonSecondaryBackground,
            buttonSecondaryForeground = LightTheme.buttonSecondaryForeground,
            dropdownBackground = LightTheme.dropdownBackground,
            dropdownForeground = LightTheme.dropdownForeground,
            dropdownBorder = LightTheme.dropdownBorder,
            listActiveBackground = LightTheme.listActiveBackground,
            listHoverBackground = LightTheme.listHoverBackground,
            badgeBackground = LightTheme.badgeBackground,
            badgeForeground = LightTheme.badgeForeground,
            divider = LightTheme.divider,
            border = LightTheme.border,
            focusBorder = LightTheme.focusBorder,
            errorForeground = LightTheme.errorForeground,
            warningForeground = LightTheme.warningForeground,
            infoForeground = LightTheme.infoForeground,
            successForeground = LightTheme.successForeground,
            scrollbarSliderBackground = LightTheme.scrollbarSliderBackground,
            scrollbarSliderHoverBackground = LightTheme.scrollbarSliderHoverBackground,
            scrollbarSliderActiveBackground = LightTheme.scrollbarSliderActiveBackground,
            menuBackground = LightTheme.menuBackground,
            menuForeground = LightTheme.menuForeground,
            menuSelectionBackground = LightTheme.menuSelectionBackground,
            notificationBackground = LightTheme.notificationBackground,
            notificationForeground = LightTheme.notificationForeground,
            keyword = LightTheme.keyword,
            string = LightTheme.string,
            number = LightTheme.number,
            comment = LightTheme.comment,
            type = LightTheme.type,
            function = LightTheme.function,
            variable = LightTheme.variable,
            constant = LightTheme.constant,
            operator = LightTheme.operator,
            className = LightTheme.className,
            parameter = LightTheme.parameter,
            property = LightTheme.property,
            regex = LightTheme.regex,
            tag = LightTheme.tag,
            attributeName = LightTheme.attributeName,
            attributeValue = LightTheme.attributeValue,
            titleBarBackground = LightTheme.titleBarBackground,
            sidebarSectionHeaderBackground = LightTheme.sidebarSectionHeaderBackground,
            sidebarSectionHeaderForeground = LightTheme.sidebarSectionHeaderForeground,
            sidebarListActiveBackground = LightTheme.sidebarListActiveBackground,
            sidebarListInactiveBackground = LightTheme.sidebarListInactiveBackground
        )

        val highContrastTheme: ThemeColors = ThemeColors(
            background = HighContrastTheme.background,
            foreground = HighContrastTheme.foreground,
            sidebarBackground = HighContrastTheme.sidebarBackground,
            activityBarBackground = HighContrastTheme.activityBarBackground,
            activityBarForeground = HighContrastTheme.activityBarForeground,
            activityBarActiveForeground = HighContrastTheme.activityBarActiveForeground,
            activityBarInactiveForeground = HighContrastTheme.activityBarInactiveForeground,
            activityBarActiveBorder = HighContrastTheme.activityBarActiveBorder,
            activityBarBadgeBackground = HighContrastTheme.activityBarBadgeBackground,
            activityBarBadgeForeground = HighContrastTheme.activityBarBadgeForeground,
            editorBackground = HighContrastTheme.editorBackground,
            editorForeground = HighContrastTheme.editorForeground,
            editorLineHighlight = HighContrastTheme.editorLineHighlight,
            editorSelectionBackground = HighContrastTheme.editorSelectionBackground,
            editorLineNumber = HighContrastTheme.editorLineNumber,
            editorLineNumberActive = HighContrastTheme.editorLineNumberActive,
            editorCursor = HighContrastTheme.editorCursor,
            editorGutterBackground = HighContrastTheme.editorGutterBackground,
            editorWidgetBackground = HighContrastTheme.editorWidgetBackground,
            statusBarBackground = HighContrastTheme.statusBarBackground,
            statusBarForeground = HighContrastTheme.statusBarForeground,
            statusBarItemHoverBackground = HighContrastTheme.statusBarItemHoverBackground,
            tabBackground = HighContrastTheme.tabBackground,
            tabActiveBackground = HighContrastTheme.tabActiveBackground,
            tabInactiveBackground = HighContrastTheme.tabInactiveBackground,
            tabActiveForeground = HighContrastTheme.tabActiveForeground,
            tabInactiveForeground = HighContrastTheme.tabInactiveForeground,
            tabActiveBorderTop = HighContrastTheme.tabActiveBorderTop,
            tabBorder = HighContrastTheme.tabBorder,
            panelBackground = HighContrastTheme.panelBackground,
            panelTitleActiveForeground = HighContrastTheme.panelTitleActiveForeground,
            panelTitleInactiveForeground = HighContrastTheme.panelTitleInactiveForeground,
            panelTitleActiveBorder = HighContrastTheme.panelTitleActiveBorder,
            panelInputBorder = HighContrastTheme.panelInputBorder,
            terminalBackground = HighContrastTheme.terminalBackground,
            terminalForeground = HighContrastTheme.terminalForeground,
            terminalAnsiBlack = HighContrastTheme.terminalAnsiBlack,
            terminalAnsiRed = HighContrastTheme.terminalAnsiRed,
            terminalAnsiGreen = HighContrastTheme.terminalAnsiGreen,
            terminalAnsiYellow = HighContrastTheme.terminalAnsiYellow,
            terminalAnsiBlue = HighContrastTheme.terminalAnsiBlue,
            terminalAnsiMagenta = HighContrastTheme.terminalAnsiMagenta,
            terminalAnsiCyan = HighContrastTheme.terminalAnsiCyan,
            terminalAnsiWhite = HighContrastTheme.terminalAnsiWhite,
            terminalAnsiBrightBlack = HighContrastTheme.terminalAnsiBrightBlack,
            terminalAnsiBrightRed = HighContrastTheme.terminalAnsiBrightRed,
            terminalAnsiBrightGreen = HighContrastTheme.terminalAnsiBrightGreen,
            terminalAnsiBrightYellow = HighContrastTheme.terminalAnsiBrightYellow,
            terminalAnsiBrightBlue = HighContrastTheme.terminalAnsiBrightBlue,
            terminalAnsiBrightMagenta = HighContrastTheme.terminalAnsiBrightMagenta,
            terminalAnsiBrightCyan = HighContrastTheme.terminalAnsiBrightCyan,
            terminalAnsiBrightWhite = HighContrastTheme.terminalAnsiBrightWhite,
            textPrimary = HighContrastTheme.textPrimary,
            textSecondary = HighContrastTheme.textSecondary,
            textDisabled = HighContrastTheme.textDisabled,
            textLink = HighContrastTheme.textLink,
            accentBlue = HighContrastTheme.accentBlue,
            accentGreen = HighContrastTheme.accentGreen,
            accentYellow = HighContrastTheme.accentYellow,
            accentRed = HighContrastTheme.accentRed,
            accentPurple = HighContrastTheme.accentPurple,
            accentCyan = HighContrastTheme.accentCyan,
            accentOrange = HighContrastTheme.accentOrange,
            inputBackground = HighContrastTheme.inputBackground,
            inputForeground = HighContrastTheme.inputForeground,
            inputBorder = HighContrastTheme.inputBorder,
            inputPlaceholderForeground = HighContrastTheme.inputPlaceholderForeground,
            inputFocusBorder = HighContrastTheme.inputFocusBorder,
            buttonBackground = HighContrastTheme.buttonBackground,
            buttonForeground = HighContrastTheme.buttonForeground,
            buttonSecondaryBackground = HighContrastTheme.buttonSecondaryBackground,
            buttonSecondaryForeground = HighContrastTheme.buttonSecondaryForeground,
            dropdownBackground = HighContrastTheme.dropdownBackground,
            dropdownForeground = HighContrastTheme.dropdownForeground,
            dropdownBorder = HighContrastTheme.dropdownBorder,
            listActiveBackground = HighContrastTheme.listActiveBackground,
            listHoverBackground = HighContrastTheme.listHoverBackground,
            badgeBackground = HighContrastTheme.badgeBackground,
            badgeForeground = HighContrastTheme.badgeForeground,
            divider = HighContrastTheme.divider,
            border = HighContrastTheme.border,
            focusBorder = HighContrastTheme.focusBorder,
            errorForeground = HighContrastTheme.errorForeground,
            warningForeground = HighContrastTheme.warningForeground,
            infoForeground = HighContrastTheme.infoForeground,
            successForeground = HighContrastTheme.successForeground,
            scrollbarSliderBackground = HighContrastTheme.scrollbarSliderBackground,
            scrollbarSliderHoverBackground = HighContrastTheme.scrollbarSliderHoverBackground,
            scrollbarSliderActiveBackground = HighContrastTheme.scrollbarSliderActiveBackground,
            menuBackground = HighContrastTheme.menuBackground,
            menuForeground = HighContrastTheme.menuForeground,
            menuSelectionBackground = HighContrastTheme.menuSelectionBackground,
            notificationBackground = HighContrastTheme.notificationBackground,
            notificationForeground = HighContrastTheme.notificationForeground,
            keyword = HighContrastTheme.keyword,
            string = HighContrastTheme.string,
            number = HighContrastTheme.number,
            comment = HighContrastTheme.comment,
            type = HighContrastTheme.type,
            function = HighContrastTheme.function,
            variable = HighContrastTheme.variable,
            constant = HighContrastTheme.constant,
            operator = HighContrastTheme.operator,
            className = HighContrastTheme.className,
            parameter = HighContrastTheme.parameter,
            property = HighContrastTheme.property,
            regex = HighContrastTheme.regex,
            tag = HighContrastTheme.tag,
            attributeName = HighContrastTheme.attributeName,
            attributeValue = HighContrastTheme.attributeValue,
            titleBarBackground = HighContrastTheme.titleBarBackground,
            sidebarSectionHeaderBackground = HighContrastTheme.sidebarSectionHeaderBackground,
            sidebarSectionHeaderForeground = HighContrastTheme.sidebarSectionHeaderForeground,
            sidebarListActiveBackground = HighContrastTheme.sidebarListActiveBackground,
            sidebarListInactiveBackground = HighContrastTheme.sidebarListInactiveBackground
        )
    }

    private object DarkTheme {
        const val background = 0xFF1E1E1E.toInt()
        const val foreground = 0xFFD4D4D4.toInt()
        const val sidebarBackground = 0xFF252526.toInt()
        const val activityBarBackground = 0xFF333333.toInt()
        const val activityBarForeground = 0xFFFFFFFF.toInt()
        const val activityBarActiveForeground = 0xFFFFFFFF.toInt()
        const val activityBarInactiveForeground = 0xFF858585.toInt()
        const val activityBarActiveBorder = 0xFFFFFFFF.toInt()
        const val activityBarBadgeBackground = 0xFF007ACC.toInt()
        const val activityBarBadgeForeground = 0xFFFFFFFF.toInt()
        const val editorBackground = 0xFF1E1E1E.toInt()
        const val editorForeground = 0xFFD4D4D4.toInt()
        const val editorLineHighlight = 0xFF2A2D2E.toInt()
        const val editorSelectionBackground = 0xFF264F78.toInt()
        const val editorLineNumber = 0xFF858585.toInt()
        const val editorLineNumberActive = 0xFFC6C6C6.toInt()
        const val editorCursor = 0xFFAEAFAD.toInt()
        const val editorGutterBackground = 0xFF1E1E1E.toInt()
        const val editorWidgetBackground = 0xFF252526.toInt()
        const val statusBarBackground = 0xFF007ACC.toInt()
        const val statusBarForeground = 0xFFFFFFFF.toInt()
        const val statusBarItemHoverBackground = 0xFFFFFF1A.toInt()
        const val tabBackground = 0xFF2D2D2D.toInt()
        const val tabActiveBackground = 0xFF1E1E1E.toInt()
        const val tabInactiveBackground = 0xFF2D2D2D.toInt()
        const val tabActiveForeground = 0xFFFFFFFF.toInt()
        const val tabInactiveForeground = 0xFF969696.toInt()
        const val tabActiveBorderTop = 0xFF007ACC.toInt()
        const val tabBorder = 0xFF252526.toInt()
        const val panelBackground = 0xFF1E1E1E.toInt()
        const val panelTitleActiveForeground = 0xFFFFFFFF.toInt()
        const val panelTitleInactiveForeground = 0xFF969696.toInt()
        const val panelTitleActiveBorder = 0xFF007ACC.toInt()
        const val panelInputBorder = 0xFF3B3B3B.toInt()
        const val terminalBackground = 0xFF1E1E1E.toInt()
        const val terminalForeground = 0xFFCCCCCC.toInt()
        const val terminalAnsiBlack = 0xFF0C0C0C.toInt()
        const val terminalAnsiRed = 0xFFC50F1F.toInt()
        const val terminalAnsiGreen = 0xFF13A10E.toInt()
        const val terminalAnsiYellow = 0xFFC19C00.toInt()
        const val terminalAnsiBlue = 0xFF0037DA.toInt()
        const val terminalAnsiMagenta = 0xFF881798.toInt()
        const val terminalAnsiCyan = 0xFF3A96DD.toInt()
        const val terminalAnsiWhite = 0xFFCCCCCC.toInt()
        const val terminalAnsiBrightBlack = 0xFF767676.toInt()
        const val terminalAnsiBrightRed = 0xFFE74856.toInt()
        const val terminalAnsiBrightGreen = 0xFF16C60C.toInt()
        const val terminalAnsiBrightYellow = 0xFFF9F1A5.toInt()
        const val terminalAnsiBrightBlue = 0xFF3B78FF.toInt()
        const val terminalAnsiBrightMagenta = 0xFFB4009E.toInt()
        const val terminalAnsiBrightCyan = 0xFF61D6D6.toInt()
        const val terminalAnsiBrightWhite = 0xFFF2F2F2.toInt()
        const val textPrimary = 0xFFCCCCCC.toInt()
        const val textSecondary = 0xFF969696.toInt()
        const val textDisabled = 0xFF5A5A5A.toInt()
        const val textLink = 0xFF3794FF.toInt()
        const val accentBlue = 0xFF007ACC.toInt()
        const val accentGreen = 0xFF6A9955.toInt()
        const val accentYellow = 0xFFDCDCAA.toInt()
        const val accentRed = 0xFFF44747.toInt()
        const val accentPurple = 0xFFC586C0.toInt()
        const val accentCyan = 0xFF4EC9B0.toInt()
        const val accentOrange = 0xFFCE9178.toInt()
        const val inputBackground = 0xFF3C3C3C.toInt()
        const val inputForeground = 0xFFCCCCCC.toInt()
        const val inputBorder = 0xFF3B3B3B.toInt()
        const val inputPlaceholderForeground = 0xFF767676.toInt()
        const val inputFocusBorder = 0xFF007ACC.toInt()
        const val buttonBackground = 0xFF007ACC.toInt()
        const val buttonForeground = 0xFFFFFFFF.toInt()
        const val buttonSecondaryBackground = 0xFF3A3D41.toInt()
        const val buttonSecondaryForeground = 0xFFCCCCCC.toInt()
        const val dropdownBackground = 0xFF252526.toInt()
        const val dropdownForeground = 0xFFCCCCCC.toInt()
        const val dropdownBorder = 0xFF454545.toInt()
        const val listActiveBackground = 0xFF094771.toInt()
        const val listHoverBackground = 0xFF2A2D2E.toInt()
        const val badgeBackground = 0xFF4D4D4D.toInt()
        const val badgeForeground = 0xFFFFFFFF.toInt()
        const val divider = 0xFF3B3B3B.toInt()
        const val border = 0xFF3B3B3B.toInt()
        const val focusBorder = 0xFF007ACC.toInt()
        const val errorForeground = 0xFFF48771.toInt()
        const val warningForeground = 0xFFCCA700.toInt()
        const val infoForeground = 0xFF75BEFF.toInt()
        const val successForeground = 0xFF89D185.toInt()
        const val scrollbarSliderBackground = 0xFF424242.toInt()
        const val scrollbarSliderHoverBackground = 0xFF4F4F4F.toInt()
        const val scrollbarSliderActiveBackground = 0xFF6E6E6E.toInt()
        const val menuBackground = 0xFF252526.toInt()
        const val menuForeground = 0xFFCCCCCC.toInt()
        const val menuSelectionBackground = 0xFF094771.toInt()
        const val notificationBackground = 0xFF252526.toInt()
        const val notificationForeground = 0xFFCCCCCC.toInt()
        const val keyword = 0xFF569CD6.toInt()
        const val string = 0xFFCE9178.toInt()
        const val number = 0xFFB5CEA8.toInt()
        const val comment = 0xFF6A9955.toInt()
        const val type = 0xFF4EC9B0.toInt()
        const val function = 0xFFDCDCAA.toInt()
        const val variable = 0xFF9CDCFE.toInt()
        const val constant = 0xFF4FC1FF.toInt()
        const val operator = 0xFFD4D4D4.toInt()
        const val className = 0xFF4EC9B0.toInt()
        const val parameter = 0xFF9CDCFE.toInt()
        const val property = 0xFF9CDCFE.toInt()
        const val regex = 0xFFD16969.toInt()
        const val tag = 0xFF569CD6.toInt()
        const val attributeName = 0xFF9CDCFE.toInt()
        const val attributeValue = 0xFFCE9178.toInt()
        const val titleBarBackground = 0xFF3C3C3C.toInt()
        const val sidebarSectionHeaderBackground = 0x80808033.toInt()
        const val sidebarSectionHeaderForeground = 0xFFBBBBBB.toInt()
        const val sidebarListActiveBackground = 0xFF37373D.toInt()
        const val sidebarListInactiveBackground = 0xFF2A2D2E.toInt()
    }

    private object LightTheme {
        const val background = 0xFFFFFFFF.toInt()
        const val foreground = 0xFF333333.toInt()
        const val sidebarBackground = 0xFFF3F3F3.toInt()
        const val activityBarBackground = 0xFFECECEC.toInt()
        const val activityBarForeground = 0xFF333333.toInt()
        const val activityBarActiveForeground = 0xFF333333.toInt()
        const val activityBarInactiveForeground = 0xFF999999.toInt()
        const val activityBarActiveBorder = 0xFF007ACC.toInt()
        const val activityBarBadgeBackground = 0xFF007ACC.toInt()
        const val activityBarBadgeForeground = 0xFFFFFFFF.toInt()
        const val editorBackground = 0xFFFFFFFF.toInt()
        const val editorForeground = 0xFF333333.toInt()
        const val editorLineHighlight = 0xFFF0F0F0.toInt()
        const val editorSelectionBackground = 0xFFADD6FF.toInt()
        const val editorLineNumber = 0xFF999999.toInt()
        const val editorLineNumberActive = 0xFF333333.toInt()
        const val editorCursor = 0xFF333333.toInt()
        const val editorGutterBackground = 0xFFFFFFFF.toInt()
        const val editorWidgetBackground = 0xFFF3F3F3.toInt()
        const val statusBarBackground = 0xFF007ACC.toInt()
        const val statusBarForeground = 0xFFFFFFFF.toInt()
        const val statusBarItemHoverBackground = 0xFF0000001A.toInt()
        const val tabBackground = 0xFFECECEC.toInt()
        const val tabActiveBackground = 0xFFFFFFFF.toInt()
        const val tabInactiveBackground = 0xFFECECEC.toInt()
        const val tabActiveForeground = 0xFF333333.toInt()
        const val tabInactiveForeground = 0xFF717171.toInt()
        const val tabActiveBorderTop = 0xFF007ACC.toInt()
        const val tabBorder = 0xFFE5E5E5.toInt()
        const val panelBackground = 0xFFFFFFFF.toInt()
        const val panelTitleActiveForeground = 0xFF333333.toInt()
        const val panelTitleInactiveForeground = 0xFF717171.toInt()
        const val panelTitleActiveBorder = 0xFF007ACC.toInt()
        const val panelInputBorder = 0xFFE5E5E5.toInt()
        const val terminalBackground = 0xFFFFFFFF.toInt()
        const val terminalForeground = 0xFF333333.toInt()
        const val terminalAnsiBlack = 0xFF0C0C0C.toInt()
        const val terminalAnsiRed = 0xFFC50F1F.toInt()
        const val terminalAnsiGreen = 0xFF13A10E.toInt()
        const val terminalAnsiYellow = 0xFFC19C00.toInt()
        const val terminalAnsiBlue = 0xFF0037DA.toInt()
        const val terminalAnsiMagenta = 0xFF881798.toInt()
        const val terminalAnsiCyan = 0xFF3A96DD.toInt()
        const val terminalAnsiWhite = 0xFF333333.toInt()
        const val terminalAnsiBrightBlack = 0xFF767676.toInt()
        const val terminalAnsiBrightRed = 0xFFE74856.toInt()
        const val terminalAnsiBrightGreen = 0xFF16C60C.toInt()
        const val terminalAnsiBrightYellow = 0xFFF9F1A5.toInt()
        const val terminalAnsiBrightBlue = 0xFF3B78FF.toInt()
        const val terminalAnsiBrightMagenta = 0xFFB4009E.toInt()
        const val terminalAnsiBrightCyan = 0xFF61D6D6.toInt()
        const val terminalAnsiBrightWhite = 0xFFF2F2F2.toInt()
        const val textPrimary = 0xFF333333.toInt()
        const val textSecondary = 0xFF717171.toInt()
        const val textDisabled = 0xFFAAAAAA.toInt()
        const val textLink = 0xFF006AB1.toInt()
        const val accentBlue = 0xFF007ACC.toInt()
        const val accentGreen = 0xFF008000.toInt()
        const val accentYellow = 0xFF795E26.toInt()
        const val accentRed = 0xFFA31515.toInt()
        const val accentPurple = 0xFFAF00DB.toInt()
        const val accentCyan = 0xFF267F99.toInt()
        const val accentOrange = 0xFFA31515.toInt()
        const val inputBackground = 0xFFFFFFFF.toInt()
        const val inputForeground = 0xFF333333.toInt()
        const val inputBorder = 0xFFE5E5E5.toInt()
        const val inputPlaceholderForeground = 0xFF999999.toInt()
        const val inputFocusBorder = 0xFF007ACC.toInt()
        const val buttonBackground = 0xFF007ACC.toInt()
        const val buttonForeground = 0xFFFFFFFF.toInt()
        const val buttonSecondaryBackground = 0xFFE5E5E5.toInt()
        const val buttonSecondaryForeground = 0xFF333333.toInt()
        const val dropdownBackground = 0xFFFFFFFF.toInt()
        const val dropdownForeground = 0xFF333333.toInt()
        const val dropdownBorder = 0xFFE5E5E5.toInt()
        const val listActiveBackground = 0xFF0060C0.toInt()
        const val listHoverBackground = 0xFFE8E8E8.toInt()
        const val badgeBackground = 0xFFCCCCCC.toInt()
        const val badgeForeground = 0xFF333333.toInt()
        const val divider = 0xFFE5E5E5.toInt()
        const val border = 0xFFE5E5E5.toInt()
        const val focusBorder = 0xFF007ACC.toInt()
        const val errorForeground = 0xFFE51400.toInt()
        const val warningForeground = 0xFFBF8803.toInt()
        const val infoForeground = 0xFF006AB1.toInt()
        const val successForeground = 0xFF388A34.toInt()
        const val scrollbarSliderBackground = 0xFFC1C1C1.toInt()
        const val scrollbarSliderHoverBackground = 0xFFA8A8A8.toInt()
        const val scrollbarSliderActiveBackground = 0xFF8E8E8E.toInt()
        const val menuBackground = 0xFFFFFFFF.toInt()
        const val menuForeground = 0xFF333333.toInt()
        const val menuSelectionBackground = 0xFF0060C0.toInt()
        const val notificationBackground = 0xFFF3F3F3.toInt()
        const val notificationForeground = 0xFF333333.toInt()
        const val keyword = 0xFF0000FF.toInt()
        const val string = 0xFFA31515.toInt()
        const val number = 0xFF098658.toInt()
        const val comment = 0xFF008000.toInt()
        const val type = 0xFF267F99.toInt()
        const val function = 0xFF795E26.toInt()
        const val variable = 0xFF001080.toInt()
        const val constant = 0xFF0070C1.toInt()
        const val operator = 0xFF333333.toInt()
        const val className = 0xFF267F99.toInt()
        const val parameter = 0xFF001080.toInt()
        const val property = 0xFF001080.toInt()
        const val regex = 0xFF811F3F.toInt()
        const val tag = 0xFF800000.toInt()
        const val attributeName = 0xFFE50000.toInt()
        const val attributeValue = 0xFF0451A5.toInt()
        const val titleBarBackground = 0xFFDDDDDD.toInt()
        const val sidebarSectionHeaderBackground = 0xFFF0F0F0.toInt()
        const val sidebarSectionHeaderForeground = 0xFF333333.toInt()
        const val sidebarListActiveBackground = 0xFFE0E0E0.toInt()
        const val sidebarListInactiveBackground = 0xFFF3F3F3.toInt()
    }

    private object HighContrastTheme {
        const val background = 0xFF000000.toInt()
        const val foreground = 0xFFFFFFFF.toInt()
        const val sidebarBackground = 0xFF000000.toInt()
        const val activityBarBackground = 0xFF000000.toInt()
        const val activityBarForeground = 0xFFFFFFFF.toInt()
        const val activityBarActiveForeground = 0xFFFFFFFF.toInt()
        const val activityBarInactiveForeground = 0xFFAAAAAA.toInt()
        const val activityBarActiveBorder = 0xFF6FC3DF.toInt()
        const val activityBarBadgeBackground = 0xFF6FC3DF.toInt()
        const val activityBarBadgeForeground = 0xFF000000.toInt()
        const val editorBackground = 0xFF000000.toInt()
        const val editorForeground = 0xFFFFFFFF.toInt()
        const val editorLineHighlight = 0xFF333333.toInt()
        const val editorSelectionBackground = 0xFF264F78.toInt()
        const val editorLineNumber = 0xFFAAAAAA.toInt()
        const val editorLineNumberActive = 0xFFFFFFFF.toInt()
        const val editorCursor = 0xFFFFFFFF.toInt()
        const val editorGutterBackground = 0xFF000000.toInt()
        const val editorWidgetBackground = 0xFF1A1A1A.toInt()
        const val statusBarBackground = 0xFF000000.toInt()
        const val statusBarForeground = 0xFFFFFFFF.toInt()
        const val statusBarItemHoverBackground = 0xFFFFFF1A.toInt()
        const val tabBackground = 0xFF000000.toInt()
        const val tabActiveBackground = 0xFF000000.toInt()
        const val tabInactiveBackground = 0xFF000000.toInt()
        const val tabActiveForeground = 0xFFFFFFFF.toInt()
        const val tabInactiveForeground = 0xFFAAAAAA.toInt()
        const val tabActiveBorderTop = 0xFF6FC3DF.toInt()
        const val tabBorder = 0xFF6FC3DF.toInt()
        const val panelBackground = 0xFF000000.toInt()
        const val panelTitleActiveForeground = 0xFFFFFFFF.toInt()
        const val panelTitleInactiveForeground = 0xFFAAAAAA.toInt()
        const val panelTitleActiveBorder = 0xFF6FC3DF.toInt()
        const val panelInputBorder = 0xFF6FC3DF.toInt()
        const val terminalBackground = 0xFF000000.toInt()
        const val terminalForeground = 0xFFFFFFFF.toInt()
        const val terminalAnsiBlack = 0xFF000000.toInt()
        const val terminalAnsiRed = 0xFFFF0000.toInt()
        const val terminalAnsiGreen = 0xFF00FF00.toInt()
        const val terminalAnsiYellow = 0xFFFFFF00.toInt()
        const val terminalAnsiBlue = 0xFF0000FF.toInt()
        const val terminalAnsiMagenta = 0xFFFF00FF.toInt()
        const val terminalAnsiCyan = 0xFF00FFFF.toInt()
        const val terminalAnsiWhite = 0xFFFFFFFF.toInt()
        const val terminalAnsiBrightBlack = 0xFF808080.toInt()
        const val terminalAnsiBrightRed = 0xFFFF0000.toInt()
        const val terminalAnsiBrightGreen = 0xFF00FF00.toInt()
        const val terminalAnsiBrightYellow = 0xFFFFFF00.toInt()
        const val terminalAnsiBrightBlue = 0xFF0000FF.toInt()
        const val terminalAnsiBrightMagenta = 0xFFFF00FF.toInt()
        const val terminalAnsiBrightCyan = 0xFF00FFFF.toInt()
        const val terminalAnsiBrightWhite = 0xFFFFFFFF.toInt()
        const val textPrimary = 0xFFFFFFFF.toInt()
        const val textSecondary = 0xFFAAAAAA.toInt()
        const val textDisabled = 0xFF666666.toInt()
        const val textLink = 0xFF6FC3DF.toInt()
        const val accentBlue = 0xFF6FC3DF.toInt()
        const val accentGreen = 0xFF6A9955.toInt()
        const val accentYellow = 0xFFDCDCAA.toInt()
        const val accentRed = 0xFFF44747.toInt()
        const val accentPurple = 0xFFC586C0.toInt()
        const val accentCyan = 0xFF4EC9B0.toInt()
        const val accentOrange = 0xFFCE9178.toInt()
        const val inputBackground = 0xFF000000.toInt()
        const val inputForeground = 0xFFFFFFFF.toInt()
        const val inputBorder = 0xFF6FC3DF.toInt()
        const val inputPlaceholderForeground = 0xFFAAAAAA.toInt()
        const val inputFocusBorder = 0xFF6FC3DF.toInt()
        const val buttonBackground = 0xFF6FC3DF.toInt()
        const val buttonForeground = 0xFF000000.toInt()
        const val buttonSecondaryBackground = 0xFF333333.toInt()
        const val buttonSecondaryForeground = 0xFFFFFFFF.toInt()
        const val dropdownBackground = 0xFF000000.toInt()
        const val dropdownForeground = 0xFFFFFFFF.toInt()
        const val dropdownBorder = 0xFF6FC3DF.toInt()
        const val listActiveBackground = 0xFF6FC3DF.toInt()
        const val listHoverBackground = 0xFF333333.toInt()
        const val badgeBackground = 0xFF6FC3DF.toInt()
        const val badgeForeground = 0xFF000000.toInt()
        const val divider = 0xFF6FC3DF.toInt()
        const val border = 0xFF6FC3DF.toInt()
        const val focusBorder = 0xFFF38518.toInt()
        const val errorForeground = 0xFFFF0000.toInt()
        const val warningForeground = 0xFFFFFF00.toInt()
        const val infoForeground = 0xFF6FC3DF.toInt()
        const val successForeground = 0xFF00FF00.toInt()
        const val scrollbarSliderBackground = 0xFF6FC3DF.toInt()
        const val scrollbarSliderHoverBackground = 0xFFFFFFFF.toInt()
        const val scrollbarSliderActiveBackground = 0xFFFFFFFF.toInt()
        const val menuBackground = 0xFF000000.toInt()
        const val menuForeground = 0xFFFFFFFF.toInt()
        const val menuSelectionBackground = 0xFF6FC3DF.toInt()
        const val notificationBackground = 0xFF000000.toInt()
        const val notificationForeground = 0xFFFFFFFF.toInt()
        const val keyword = 0xFF569CD6.toInt()
        const val string = 0xFFCE9178.toInt()
        const val number = 0xFFB5CEA8.toInt()
        const val comment = 0xFF6A9955.toInt()
        const val type = 0xFF4EC9B0.toInt()
        const val function = 0xFFDCDCAA.toInt()
        const val variable = 0xFF9CDCFE.toInt()
        const val constant = 0xFF4FC1FF.toInt()
        const val operator = 0xFFFFFFFF.toInt()
        const val className = 0xFF4EC9B0.toInt()
        const val parameter = 0xFF9CDCFE.toInt()
        const val property = 0xFF9CDCFE.toInt()
        const val regex = 0xFFD16969.toInt()
        const val tag = 0xFF569CD6.toInt()
        const val attributeName = 0xFF9CDCFE.toInt()
        const val attributeValue = 0xFFCE9178.toInt()
        const val titleBarBackground = 0xFF000000.toInt()
        const val sidebarSectionHeaderBackground = 0xFF333333.toInt()
        const val sidebarSectionHeaderForeground = 0xFFFFFFFF.toInt()
        const val sidebarListActiveBackground = 0xFF6FC3DF.toInt()
        const val sidebarListInactiveBackground = 0xFF000000.toInt()
    }
}